language: ruby
rvm:
- 2.5.1
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  run: rake db:migrate
  app: krk-18-xmen
  api_key:
    secure: N3UvcH/Jqc37L3itHue4aKCDK0qVyJFDIYsuMzca/lLfhPQaYpNmfp6HXHcOE7ocN/Gx49MzpABFrFn18WRpiCn6BKFD5eDF/5ZkCLW25Hv+SLYjpaOeAp3Yk86lzHD1skJJ1vsZo1A6Yes4vIdCyURYJmerPQRTDcuiUvWf52cn7suwtoK1xIGBvyL+XJt5iFwFqFT95QtVuUzgvN0IUoQKOhVNjn9eKYRVLSj041j6OgGnAEbaoZLCvmEkaghP0Q7EF5eDvHixeOTtdEQQ7BVzkPB8ptMoZt+dsbIK6JrAVnx8IF0GxfYZdViikYH6K/69cRzo6jmVr3xY694838UZ1EKstiQuLAO5oiMEiKz5lVpy3J3T2pPab6nYPOH+eyRgGX0wSSou4Q1SiIIgC8UpsRUPqu19WyXJSGdVy2O6ugLFwrxDnXU0RZiM4B6lkHhEDyLZTOakbQjN4peBvuyXRrnw19tFjI2X9nxr3t5D78RIHHuifyQ+6sODiIWnrqnxo0i+0OYj+GFHreWaeU6IX5OPmQaoH1RX4ms08FYvmRgfR6SKSG1t7X/Sv3r2Qsrfqyps2WdLhKXtkiggiCLlU/+qsEEd6psUNIsjDAYX5pcgkXuTUSJBfXssCXuWfSxIf6xsqwGUnd8v1AkadlGftAqkuB/cdIcSTrzrDW8=
  on:
    repo: netguru-code-college/krk-18-xmen
